-- Categories
INSERT INTO Category (Name) VALUES ('Business');
INSERT INTO Category (Name) VALUES ('Easy');
INSERT INTO Category (Name) VALUES ('Her');
INSERT INTO Category (Name) VALUES ('Democrat');
INSERT INTO Category (Name) VALUES ('Debate');
INSERT INTO Category (Name) VALUES ('Inside');
INSERT INTO Category (Name) VALUES ('Subject');
INSERT INTO Category (Name) VALUES ('Argue');
INSERT INTO Category (Name) VALUES ('View');
INSERT INTO Category (Name) VALUES ('Stand');
INSERT INTO Category (Name) VALUES ('Draw');
INSERT INTO Category (Name) VALUES ('Me');
INSERT INTO Category (Name) VALUES ('Two');
INSERT INTO Category (Name) VALUES ('Simply');
INSERT INTO Category (Name) VALUES ('Statement');
INSERT INTO Category (Name) VALUES ('Produce');
INSERT INTO Category (Name) VALUES ('Clearly');
INSERT INTO Category (Name) VALUES ('Check');
INSERT INTO Category (Name) VALUES ('Partner');
INSERT INTO Category (Name) VALUES ('Environmental');
INSERT INTO Category (Name) VALUES ('Minute');
INSERT INTO Category (Name) VALUES ('News');
INSERT INTO Category (Name) VALUES ('Analysis');
INSERT INTO Category (Name) VALUES ('Foot');
INSERT INTO Category (Name) VALUES ('Process');
INSERT INTO Category (Name) VALUES ('Research');
INSERT INTO Category (Name) VALUES ('Trial');
INSERT INTO Category (Name) VALUES ('Natural');
INSERT INTO Category (Name) VALUES ('Lay');
INSERT INTO Category (Name) VALUES ('Year');

-- Vendors
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Mccormick-Mora', 'colemanpamela@hawkins.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Mcdaniel-Francis', 'brittanyblankenship@perry-rogers.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Walters-Mitchell', 'denise14@bell.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Moreno Inc', 'nicholas45@moore-mora.biz');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Murray Inc', 'mcampbell@smith.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Thompson, Martin and Clark', 'diana14@gomez.biz');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Williams and Sons', 'qlowe@cook-lee.info');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Williams LLC', 'george22@garcia.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Newton, Andrews and Brown', 'ashley07@santiago.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Reeves, Weber and Perez', 'mortoncorey@ortiz.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Jennings, Diaz and Williams', 'zscott@brown-cooke.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Lopez, Ruiz and Boyer', 'patrick60@sandoval-middleton.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Smith LLC', 'denise71@smith-alvarez.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Garcia, Smith and Johnson', 'jamesellis@larson.org');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Richardson, Haney and Page', 'tgreen@ross.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Daniels, Hill and Wilson', 'suzannewoods@curtis.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Rogers-Copeland', 'medinamichelle@lara.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Olson, Robertson and Campbell', 'nicholas74@lam.net');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Perkins and Sons', 'jessicajackson@parker.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Bell-Olson', 'hurstvictoria@dorsey.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Montgomery-Stevens', 'fyork@hamilton-lloyd.info');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Schneider Ltd', 'chanjason@ortiz.info');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Martinez-Brown', 'emily35@hart.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Dunn, Bishop and Mcbride', 'meganmiller@martinez.net');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Brooks, Morris and Bruce', 'edwardsdonald@anderson-stewart.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Armstrong LLC', 'joshua53@perez-romero.biz');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Clarke Inc', 'laurenjohnson@holland.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Flynn-Morris', 'amanda70@vaughn.com');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Roy-Miller', 'christophervilla@doyle-williams.net');
INSERT INTO Vendor (VendorName, ContactInfo) VALUES ('Ponce Ltd', 'robinsonalan@wilson-riley.com');

-- Books
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Shake use.', 'Brian Reed', '9781930271456', 41.36, 'Character gas by rate. Eight hospital decision care wear energy.', 'in.jpg', 23, 28);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Reflect.', 'Kimberly Baker', '9780039558734', 26.71, 'Across including school activity general interview. Guess develop someone boy do Mr side outside.', 'game.jpg', 13, 25);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Television young talk.', 'Kevin Marsh', '9781287237068', 45.09, 'Whose detail land girl everyone. Understand surface building son doctor. Close article school.', 'else.jpg', 22, 24);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Despite key brother.', 'Curtis Valdez', '9781825738538', 26.66, 'Thought quickly blood continue section mind. Job TV such none meeting. Add radio finish then there.', 'painting.jpg', 11, 26);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Window environment.', 'John Dougherty', '9781714120598', 41.58, 'Figure better fall all. Development reach wish bit.', 'do.jpg', 15, 1);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Modern early baby.', 'Donald Ayers', '9780754634782', 8.25, 'Skin store young long. Land late mission.', 'today.jpg', 2, 13);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Since place force though.', 'Donald Rivera', '9780582534384', 44.61, 'Prevent reveal debate me. State service serious too.', 'something.jpg', 17, 26);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('System tend respond.', 'Sarah Webb', '9780418672747', 22.21, 'During security middle smile me. Each several million expect.', 'south.jpg', 24, 23);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Next on factor.', 'Richard Zimmerman', '9780887985744', 10.56, 'At prevent green run happen some. Example even structure heavy offer control. Rock such senior.', 'all.jpg', 24, 4);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Treat time change.', 'Luis Taylor', '9780111380642', 23.87, 'Ready child difference. Less might out really true program our.', 'job.jpg', 16, 12);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Professor heart.', 'Darius Bishop', '9781722789909', 35.24, 'Again option level question focus low. Staff season audience center beat.', 'fear.jpg', 27, 16);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Make.', 'James Lester', '9781885052858', 42.1, 'Well lose town short none Mrs. Power view anyone own wall.', 'fire.jpg', 30, 20);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Other relationship blue wrong.', 'Mario Kelley', '9781503840720', 35.59, 'International crime culture together. Simply meeting stand on media. Audience amount who agency.', 'room.jpg', 9, 27);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Me hair.', 'Daniel Davis', '9781077655911', 46.67, 'Care college American wide. Career who expect political five.', 'out.jpg', 22, 26);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Set wind.', 'Kim Ray', '9781648573941', 24.63, 'Walk do million factor keep guess south. Chance meeting question executive argue class alone small.', 'up.jpg', 26, 6);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Race serve.', 'Harold Reed', '9781698265636', 21.14, 'Right write decision measure body. Notice position stop movement truth early.', 'body.jpg', 4, 26);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Husband seven.', 'Michelle Dean', '9781802474848', 13.57, 'Day Democrat condition full account how individual. Where even fly allow.', 'trade.jpg', 22, 5);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Meeting scene TV.', 'Michael Gomez', '9781313533881', 40.65, 'Still author out yeah. Personal big base consider everything boy.', 'half.jpg', 30, 25);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Weight.', 'Mr. William Barajas PhD', '9781183815261', 11.47, 'Range local lose phone. Treatment worker increase friend without others whom.', 'Congress.jpg', 21, 23);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Offer option.', 'April Gibson', '9781634082532', 46.24, 'Cup step together hope poor consider market report. Three yourself effect.', 'poor.jpg', 25, 2);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('New quite.', 'Wendy Rhodes', '9781755840400', 34.65, 'Much may billion same not hit exactly. With expert same several nothing few air guy.', 'take.jpg', 20, 23);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Paper unit.', 'Ronald Taylor', '9781936731268', 17.7, 'Every listen data effect. Activity begin become activity indeed system actually reason.', 'fear.jpg', 8, 13);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Garden fear.', 'Maria Jordan', '9781577434061', 14.29, 'Visit factor letter through. Station rather act describe everyone.', 'data.jpg', 4, 28);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Once hand authority despite.', 'Mrs. Caitlyn George', '9781660823642', 33.54, 'American work group news choose listen.', 'avoid.jpg', 30, 2);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Five dinner.', 'David Rodriguez', '9781982057596', 18.36, 'Her clear so another. Several prepare stock miss. Then chance probably everything camera.', 'western.jpg', 21, 17);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Service newspaper wear.', 'Robert Brown', '9780541593407', 41.26, 'Speak here condition hand need sport goal describe. Appear where above environmental sense every.', 'someone.jpg', 4, 10);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Home similar dark.', 'Nathan Page', '9781761858086', 13.45, 'Statement scientist sell network them western such his. People peace face community real increase.', 'almost.jpg', 23, 25);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Expect fall business.', 'Chris Hicks', '9781078271264', 9.71, 'Rise full shake state. Team soldier thought listen option financial official.', 'yard.jpg', 29, 15);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Base church never.', 'Thomas Romero', '9780433443773', 38.93, 'Tough reduce office. Thus visit administration usually.', 'his.jpg', 29, 8);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('He hospital.', 'Christine Dunn', '9781457325694', 19.37, 'Clear key most film artist buy. Behavior answer west agree. Those find from start.', 'thousand.jpg', 17, 8);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Late important special.', 'Scott Pierce', '9781091674165', 26.06, 'Story race church wife look here.
Eat anyone early particular. Spend sport as price brother.', 'his.jpg', 23, 2);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Single about despite.', 'Curtis Kane', '9780721576701', 14.81, 'This save goal these mother skin. Often region make behavior. Contain home ago political.', 'impact.jpg', 3, 27);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Surface claim.', 'Justin Williams', '9780561405223', 17.81, 'May boy forget magazine role down around listen.', 'as.jpg', 17, 24);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Community sure price third.', 'Elizabeth Russell', '9780400737416', 34.11, 'Product work thing hot social. Every town prove six wind.', 'hope.jpg', 7, 30);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Computer beyond add.', 'Dylan Smith', '9781147678048', 43.08, 'Education market west she culture because car. Sister bag experience course perhaps.', 'return.jpg', 6, 26);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Treat ability home.', 'Bruce Elliott', '9780656555079', 17.3, 'Peace pressure political take. Adult blood center people. Ok officer ahead approach may market.', 'something.jpg', 17, 22);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Activity put.', 'Shannon Walker', '9780462116822', 9.52, 'Tonight behavior experience half newspaper oil community. Already concern drop audience value.', 'tonight.jpg', 18, 26);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('You.', 'James Richards', '9781504244473', 15.5, 'Happen college field factor. Type ability pick. Weight money east important memory.', 'when.jpg', 29, 10);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Long.', 'James Ewing', '9780575447455', 46.07, 'Probably girl issue card. Into will person.', 'she.jpg', 16, 10);
INSERT INTO Book (Title, Author, ISBN, Price, Description, CoverImage, CategoryID, VendorID) VALUES ('Data stand another.', 'Tracy Russell DDS', '9781291570984', 28.8, 'Late save set be term. Administration relate similar might suffer when.', 'past.jpg', 18, 11);

-- Customers
INSERT INTO Customer (Name, Email, Password) VALUES ('William Moore', 'fitzpatricktrevor@example.com', 'A8(Xpir5(2HJ');
INSERT INTO Customer (Name, Email, Password) VALUES ('Tricia Ferguson', 'smithpeter@example.org', 'UF(u4KybJgs!');
INSERT INTO Customer (Name, Email, Password) VALUES ('Cassandra Clark', 'robinsonjonathan@example.com', '1$PDRly&xl9V');
INSERT INTO Customer (Name, Email, Password) VALUES ('Jennifer Andrews', 'matthewbrown@example.net', '28WX#l_a_@RX');
INSERT INTO Customer (Name, Email, Password) VALUES ('Courtney Miller', 'jenniferbell@example.org', 'hq_vWVfw_a7S');
INSERT INTO Customer (Name, Email, Password) VALUES ('Ricky Price', 'atorres@example.org', 'kl$5Rvu!YI*f');
INSERT INTO Customer (Name, Email, Password) VALUES ('Heather Sanchez', 'cassidy50@example.org', ')nWHRCVYR29B');
INSERT INTO Customer (Name, Email, Password) VALUES ('John Shepherd', 'mberry@example.com', 'Q6M%xTnH+Jhn');
INSERT INTO Customer (Name, Email, Password) VALUES ('Sharon Webster', 'emckee@example.org', '%7%O*rv4CuRl');
INSERT INTO Customer (Name, Email, Password) VALUES ('Levi Sanchez', 'justin34@example.net', 'ak+IVvl)U9G1');
INSERT INTO Customer (Name, Email, Password) VALUES ('Jaime Mueller', 'gatesmegan@example.com', 'm4l&vfWw$4Pz');
INSERT INTO Customer (Name, Email, Password) VALUES ('Alan Clark', 'hurleyanthony@example.com', 'Z()VXLeP&wK7');
INSERT INTO Customer (Name, Email, Password) VALUES ('Monica Rodriguez', 'jessicaharmon@example.net', '9M_I0lLk%bPE');
INSERT INTO Customer (Name, Email, Password) VALUES ('Anthony Shaffer', 'savannahnichols@example.com', '%G52fNflL4QO');
INSERT INTO Customer (Name, Email, Password) VALUES ('Donna Chapman', 'steven97@example.net', '+_!*RYah2j8v');
INSERT INTO Customer (Name, Email, Password) VALUES ('Lisa Alexander', 'megan39@example.net', '#)1%I#jeWdVm');
INSERT INTO Customer (Name, Email, Password) VALUES ('Earl Watson', 'wjones@example.com', 'IGR@k@jF)#8D');
INSERT INTO Customer (Name, Email, Password) VALUES ('Grace Day', 'barrettbrittney@example.org', 'A7G3kRKK$tWk');
INSERT INTO Customer (Name, Email, Password) VALUES ('Nicole Heath', 'johnssandra@example.net', 'r7@^E%$C%dTV');
INSERT INTO Customer (Name, Email, Password) VALUES ('Raymond Tucker', 'duncanerica@example.org', 'P%q9RYAd_4^q');
INSERT INTO Customer (Name, Email, Password) VALUES ('Paul Jimenez', 'wigginsstanley@example.org', 'PMU1EL)f!3x&');
INSERT INTO Customer (Name, Email, Password) VALUES ('Michael James', 'benjamindavis@example.org', '!ip^H#O*)3A!');
INSERT INTO Customer (Name, Email, Password) VALUES ('Johnny Barnes', 'ldavis@example.com', 't8X(gI_C9$Cp');
INSERT INTO Customer (Name, Email, Password) VALUES ('Alexis Rodgers PhD', 'rlewis@example.org', 'Aud8Imp0KI!q');
INSERT INTO Customer (Name, Email, Password) VALUES ('Louis Sanchez', 'adrianlee@example.com', '0F7JBhgS#OS!');
INSERT INTO Customer (Name, Email, Password) VALUES ('Cory Ramirez', 'anthony18@example.org', 'ih8EUy$+^!7e');
INSERT INTO Customer (Name, Email, Password) VALUES ('Joshua Baker', 'maria54@example.org', 'a)5q$ZgP*!P_');
INSERT INTO Customer (Name, Email, Password) VALUES ('Caitlyn Acosta', 'millertrevor@example.com', 'L)e4Wsp@+k2!');
INSERT INTO Customer (Name, Email, Password) VALUES ('Robert Warren', 'martinhill@example.org', '9!6n0Pm6j_TY');
INSERT INTO Customer (Name, Email, Password) VALUES ('Melinda Carpenter', 'anne44@example.net', '81%uddtm(RbL');
INSERT INTO Customer (Name, Email, Password) VALUES ('Katie Manning', 'erinfischer@example.net', '!d7xWDpo_zAK');
INSERT INTO Customer (Name, Email, Password) VALUES ('Christopher Richards', 'mccallmatthew@example.org', '4nQZk!5h$B%F');
INSERT INTO Customer (Name, Email, Password) VALUES ('Patricia Lawrence DDS', 'lshaw@example.net', 'S+qI7d+Tt910');
INSERT INTO Customer (Name, Email, Password) VALUES ('Brianna Todd', 'jorgemason@example.com', '_0C)VzpW%eUI');
INSERT INTO Customer (Name, Email, Password) VALUES ('Melissa Cruz', 'kristina39@example.net', 'Hk6Bwqx$$%KZ');
INSERT INTO Customer (Name, Email, Password) VALUES ('Amanda Meyer', 'breannamurphy@example.com', 'I4Qfvnfx+7F5');
INSERT INTO Customer (Name, Email, Password) VALUES ('Amy Cuevas', 'hawkinsmichelle@example.net', '5!2^Fi(9jdiW');
INSERT INTO Customer (Name, Email, Password) VALUES ('Michelle Kennedy', 'guerrabryan@example.org', '(MpRqB4nq5oj');
INSERT INTO Customer (Name, Email, Password) VALUES ('Amanda Barker', 'timothy58@example.org', '(*9OIqf*e_MT');
INSERT INTO Customer (Name, Email, Password) VALUES ('Rebecca Bright', 'anna39@example.net', '#0QXlvHqAHUG');

-- Orders
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (28, 'Shipped', 104.33, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (29, 'Shipped', 16.52, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (2, 'Shipped', 184.97, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (27, 'Cancelled', 94.77, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (5, 'Shipped', 55.84, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (33, 'Processing', 192.01, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (25, 'Shipped', 194.61, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (25, 'Delivered', 145.03, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (7, 'Cancelled', 154.13, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (1, 'Delivered', 48.43, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (29, 'Delivered', 127.63, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (19, 'Processing', 166.17, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (20, 'Shipped', 129.93, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (6, 'Processing', 54.57, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (14, 'Delivered', 160.9, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (13, 'Cancelled', 167.02, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (4, 'Shipped', 61.15, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (20, 'Processing', 124.19, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (13, 'Delivered', 119.27, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (28, 'Shipped', 121.99, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (8, 'Cancelled', 107.44, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (18, 'Delivered', 158.57, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (1, 'Delivered', 195.88, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (34, 'Processing', 30.55, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (26, 'Delivered', 168.17, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (8, 'Cancelled', 100.63, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (3, 'Cancelled', 32.9, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (4, 'Shipped', 94.37, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (28, 'Processing', 46.38, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (9, 'Cancelled', 165.87, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (19, 'Delivered', 165.78, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (24, 'Processing', 184.79, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (3, 'Cancelled', 146.46, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (13, 'Shipped', 87.23, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (19, 'Cancelled', 152.03, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (20, 'Shipped', 13.67, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (10, 'Cancelled', 82.19, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (21, 'Cancelled', 24.55, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (30, 'Processing', 177.99, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (3, 'Delivered', 104.63, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (21, 'Processing', 122.69, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (37, 'Shipped', 182.32, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (33, 'Delivered', 82.79, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (34, 'Shipped', 140.34, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (28, 'Delivered', 164.84, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (18, 'Processing', 63.02, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (13, 'Delivered', 98.63, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (34, 'Shipped', 93.54, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (40, 'Shipped', 58.38, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (4, 'Processing', 16.93, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (31, 'Cancelled', 32.69, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (11, 'Processing', 109.2, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (34, 'Processing', 151.63, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (39, 'Cancelled', 45.83, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (30, 'Delivered', 41.04, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (2, 'Processing', 130.99, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (36, 'Delivered', 140.96, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (1, 'Shipped', 41.22, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (23, 'Processing', 144.84, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (27, 'Cancelled', 112.13, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (37, 'Processing', 44.51, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (3, 'Processing', 28.87, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (8, 'Delivered', 48.56, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (38, 'Processing', 131.08, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (19, 'Shipped', 191.6, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (10, 'Delivered', 53.98, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (28, 'Cancelled', 193.41, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (10, 'Shipped', 41.61, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (34, 'Shipped', 142.65, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (17, 'Cancelled', 80.42, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (33, 'Delivered', 67.01, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (31, 'Shipped', 152.64, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (5, 'Cancelled', 191.06, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (6, 'Processing', 138.82, '2025-04-23');
INSERT INTO `Order` (CustomerID, Status, TotalAmount, OrderDate) VALUES (12, 'Shipped', 199.15, '2025-04-23');

-- OrderDetails
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (64, 40, 4, 28.74);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (33, 39, 5, 48.69);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (5, 5, 3, 41.42);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (56, 2, 2, 5.97);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (21, 18, 5, 21.84);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (2, 28, 1, 25.23);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (1, 29, 5, 46.77);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (28, 7, 2, 47.41);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (43, 35, 2, 43.33);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (34, 25, 5, 13.99);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (62, 18, 2, 32.09);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (35, 34, 5, 47.45);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (68, 11, 4, 8.38);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (57, 31, 4, 11.71);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (46, 1, 2, 36.32);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (19, 15, 2, 10.73);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (52, 29, 2, 19.76);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (30, 39, 5, 28.95);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (45, 16, 3, 8.15);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (23, 25, 1, 25.29);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (67, 2, 2, 41.41);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (19, 40, 4, 46.79);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (22, 33, 3, 32.82);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (43, 6, 4, 40.32);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (62, 1, 5, 9.76);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (5, 31, 3, 17.68);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (42, 30, 5, 39.29);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (5, 8, 1, 10.02);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (38, 37, 3, 9.76);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (15, 4, 1, 6.51);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (27, 21, 5, 27.7);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (38, 37, 2, 14.33);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (64, 14, 4, 36.84);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (43, 2, 4, 7.41);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (15, 17, 5, 45.27);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (51, 3, 3, 20.86);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (55, 8, 1, 44.43);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (23, 3, 5, 21.13);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (22, 23, 3, 11.43);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (59, 29, 1, 47.0);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (36, 20, 2, 15.89);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (12, 11, 4, 10.3);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (47, 13, 2, 8.95);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (59, 14, 1, 20.89);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (26, 34, 1, 20.94);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (62, 16, 2, 42.4);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (40, 7, 1, 40.43);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (16, 26, 4, 48.26);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (14, 21, 3, 47.99);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (54, 15, 3, 38.37);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (48, 40, 3, 42.52);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (13, 40, 2, 28.68);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (60, 11, 5, 49.65);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (69, 16, 1, 9.53);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (19, 2, 5, 28.84);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (11, 29, 3, 12.7);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (29, 28, 3, 32.66);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (20, 20, 1, 20.35);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (43, 39, 1, 44.23);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (47, 30, 1, 37.8);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (60, 11, 5, 31.95);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (23, 3, 4, 39.3);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (28, 2, 1, 21.5);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (31, 5, 4, 43.11);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (65, 36, 4, 49.73);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (26, 37, 3, 26.36);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (66, 3, 3, 9.71);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (2, 16, 2, 6.83);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (65, 14, 1, 36.79);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (14, 20, 2, 48.79);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (59, 30, 4, 24.23);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (8, 33, 1, 40.59);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (21, 39, 5, 40.18);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (14, 15, 3, 17.95);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (53, 13, 2, 31.88);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (61, 31, 4, 33.85);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (11, 37, 5, 6.07);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (21, 11, 4, 38.13);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (3, 11, 4, 26.68);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (57, 6, 2, 23.3);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (19, 35, 4, 11.55);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (32, 31, 1, 33.71);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (3, 25, 1, 32.21);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (73, 2, 3, 27.6);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (18, 7, 5, 15.75);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (57, 20, 5, 34.73);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (19, 31, 5, 48.13);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (15, 2, 1, 12.75);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (58, 24, 1, 32.58);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (9, 14, 1, 47.74);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (27, 13, 2, 5.59);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (56, 33, 4, 15.84);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (66, 36, 5, 16.34);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (54, 15, 4, 6.91);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (6, 33, 2, 9.68);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (55, 17, 5, 6.25);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (24, 27, 2, 13.49);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (44, 38, 2, 24.26);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (12, 5, 2, 37.33);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (18, 16, 2, 23.02);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (39, 37, 5, 38.8);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (57, 24, 1, 40.78);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (42, 33, 2, 36.61);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (73, 9, 1, 31.63);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (25, 37, 4, 35.44);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (14, 34, 3, 5.04);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (12, 12, 2, 36.62);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (63, 34, 4, 36.45);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (17, 39, 3, 30.47);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (35, 23, 1, 27.31);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (48, 12, 3, 6.87);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (63, 36, 2, 13.61);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (1, 1, 1, 8.56);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (72, 29, 2, 47.25);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (4, 32, 3, 26.27);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (73, 5, 2, 34.37);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (60, 18, 5, 18.24);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (35, 28, 3, 16.72);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (74, 8, 2, 5.39);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (51, 17, 3, 10.58);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (59, 26, 2, 7.94);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (59, 15, 4, 14.5);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (22, 19, 2, 26.08);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (47, 15, 1, 30.58);
INSERT INTO OrderDetail (OrderID, BookID, Quantity, Price) VALUES (68, 20, 1, 22.09);

-- Inventory
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (1, 99, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (2, 9, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (3, 58, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (4, 26, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (5, 33, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (6, 45, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (7, 94, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (8, 64, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (9, 86, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (10, 70, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (11, 55, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (12, 96, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (13, 94, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (14, 10, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (15, 68, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (16, 38, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (17, 71, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (18, 100, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (19, 36, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (20, 21, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (21, 54, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (22, 65, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (23, 92, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (24, 62, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (25, 74, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (26, 70, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (27, 51, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (28, 87, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (29, 20, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (30, 26, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (31, 95, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (32, 50, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (33, 78, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (34, 51, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (35, 48, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (36, 77, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (37, 71, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (38, 45, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (39, 9, '2025-04-23');
INSERT INTO Inventory (BookID, StockQuantity, LastRestockedDate) VALUES (40, 26, '2025-04-23');
